### ISSUE TITLE
Unable to remove app from Gitter Developer

### ISSUE THREAD

**Issue by haydenhancock** [gitterHQ/docs#56] opened 2017-11-02 21:28 UTC
I am unable to remove an application from Gitter Developer. I get a 404.

**Comment by MadLittleMods** [comment] 2017-11-03 01:57
Wrong repo to report issues on 🙇 

Duplicate of https://gitlab.com/gitlab-org/gitter/webapp/issues/1153

**Closed by MadLittleMods** 2017-11-03 01:57 UTC
