### ISSUE TITLE
Deleting an app gives 404

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/docs#49] opened 2016-10-30 21:12 UTC
I created a test app on https://developer.gitter.im and when i click "delete" i get a 404 page and the app hasnt deleted

![image](https://cloud.githubusercontent.com/assets/14148452/19840042/817a7162-9ee5-11e6-9298-5695c700e8d8.png)

**Comment by MadLittleMods** [comment] 2016-10-31 03:04
This is on the wrong project and is a duplicate of https://github.com/gitterHQ/gitter/issues/1153

**Closed by MadLittleMods** 2016-10-31 03:04 UTC

**Comment by TheDiamondYT1** [comment] 2016-11-01 15:57
I was told to file here by mydigitalself
